name: cyr
description: CYR信息采集APP

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^3.0.1+6
  photo_view: any
  path_provider: any
  json_annotation: any



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 状态管理
  provider: ^4.3.2+2
  # 本地存储
  shared_preferences: ^0.5.12+4
  # 检测网络状态
  connectivity: ^2.0.1
  # 图片选择
  image_picker: ^0.6.7+12
  # 二维码扫描和生成
  qrscan: ^0.2.17
  scan: ^0.0.6
  permission_handler: ^5.1.0+2
  # 图表
  syncfusion_flutter_charts: ^18.4.34
  #  CloudBase
  cloudbase_core: ^0.0.11
  cloudbase_auth: ^0.0.14
  cloudbase_database: ^0.0.12
  cloudbase_storage: ^0.0.3
  cloudbase_function: ^0.0.2
  # 拨号
  url_launcher: ^5.7.10
  # svg
  flutter_svg: ^0.19.1
  # 获取包名
  package_info: ^0.4.3+2
  # 弹窗提示
  toast: ^0.1.5
  # 本地验证
  local_auth: ^0.6.3+4
  # OCR识别
  flutter_tencent_ocr: ^0.1.2
  # 设备信息
  device_info: ^1.0.0
  # 页面切换过渡动画
  page_transition: ^1.1.7+2
  # 刷新与加载
  # pull_to_refresh: ^1.6.3
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # icon
     - assets/icons/male.svg
     - assets/icons/female.svg
     - assets/icons/doctor_female.svg
     - assets/icons/doctor_male.svg
     # 图片
     - assets/images/male.png
     - assets/images/female.png
     - assets/images/aspect.png
     - assets/images/aspect01.png
     - assets/images/aspect02.png
     - assets/images/aspect03.png
     - app_config.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
